foggyline_catalog_product:
    resource: "@FoggylineCatalogBundle/Controller/ProductController.php"
    type:     annotation

foggyline_catalog_category:
    resource: "@FoggylineCatalogBundle/Controller/CategoryController.php"
    type:     annotation

foggyline_catalog:
    resource: "@FoggylineCatalogBundle/Resources/config/routing.xml"
    prefix:   /catalog/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
